version: '3'
services:
  server:
    build: .
    ports:
    - "8080:8080"
    links:
      - database
    depends_on:
      - "database"
    command: ["./wait-for-it.sh", "-h", "database", "-p", "5432"]
  database:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=demodb
      - POSTGRES_USER=postgres

