version: '3'
services:
  server:
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - database
  database:
    restart: always
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=demodb
      - POSTGRES_USER=postgres

